### PR TITLE
[SQTA-4] [TEAM B] Find Owners Page

### PR DESCRIPTION
**Pull request by KristianKurk**
This verifies that the user is successfully taken to the Find Owners page when the appropriate link is clicked.

### CODE REVIEW

**Review by RemiJonathan — APPROVED** [review]

**Review by danyyilbun — DISMISSED** [review]

**Review by iburov — DISMISSED** [review]

**Review by cgerard321 — DISMISSED** [review]
LGTM

**Comment by cgerard321** [comment]
Done

**Review by jason-gerard — DISMISSED** [review]
Localhost6969 👌🏼👌🏼

**Review by RemiJonathan — DISMISSED** [review]
LGTM

**Review by RemiJonathan — APPROVED** [review]
LGTM

**Comment by Mino-Mes** [comment]
Looks Good

**Review by Mino-Mes — APPROVED** [review]
Good Job

**Review by RemiJonathan — APPROVED** [review]
LGTM

**Review by RemiJonathan — APPROVED** [review]
LGTM

**Review by Mino-Mes — APPROVED** [review]

**Review by Mino-Mes — APPROVED** [review]
Great Work

**Review by danyyilbun — APPROVED** [review]

**Pull request merged**
