### PR TITLE
[STQA-26][TEAM C] processFunction() returns correct path on valid input

### PR DESCRIPTION
**Pull request by LVoisard**
Added a test function to verify that when a user uses the processFunction() with a valid result int hte Binding result returns the right form

### CODE REVIEW

**Review by horiasandu1 — DISMISSED** [review]
Everything looks good. Bless.

**Comment by Cessalan** [comment]
Looks good to me. Nice Job!

**Review by ben-cl — DISMISSED** [review]
Good! Work as intended! Can add a description

**Review by Cessalan — DISMISSED** [review]

**Review by ben-cl — APPROVED** [review]
Good! Work as intended! Can add a description

**Review by HaroonMas — DISMISSED** [review]
Good work Champ 😘

**Review by ben-cl — DISMISSED** [review]
Excellent work!!!!

**Review by horiasandu1 — APPROVED** [review]
conflict resolved

**Comment by ben-cl** [comment]
Excellent!!

**Review by ben-cl — APPROVED** [review]
Excellent!!

**Pull request merged**
