### PR TITLE
[SQTA-29] [TEAM C] As a user, I want to be able to see a list of all owners by clicking search without entering a last name 

### PR DESCRIPTION
**Pull request by ben-cl**
SQTA-29 Test method see list all owners selenium

As a user, I want to be able to see a list of all owners by clicking search without entering a last name

### CODE REVIEW

**Review by Cessalan — DISMISSED** [review]
good

**Review by LVoisard — DISMISSED** [review]
Nice work

**Review by namisabet — DISMISSED** [review]
Looks good Team C!

**Review by namisabet — APPROVED** [review]
Thumbs up

**Review by LVoisard — APPROVED** [review]
GOOD

**Pull request merged**
