### PR TITLE
[STQA-9] [Team B] as a user, I want to be able to add an owner.

### PR DESCRIPTION
**Pull request by RemiJonathan**

### CODE REVIEW

**Review by KristianKurk — DISMISSED** [review]
I don't understand the whole cow bit, but the rest looks good.

**Review by danyyilbun — DISMISSED** [review]
LGTM

**Review by Mino-Mes — DISMISSED** [review]
Good job

**Review by KristianKurk — APPROVED** [review]
no cows, hurray!

**Review by danyyilbun — APPROVED** [review]

**Pull request merged**
