### PR TITLE
[SQTA-22] [TEAM C] Completed test method for when there is an error in the method to update the pet.

### PR DESCRIPTION
**Pull request by horiasandu1**
By using the processUpdateForm() method in the petController, you can update a pet. This test assures that if the result (input validation) has errors, the appropriate methods are called and no invalid changes are saved.

### CODE REVIEW

**Review by LVoisard — DISMISSED** [review]
you should arrange all your variables at the top of your function but the function looks good!

**Review by ben-cl — DISMISSED** [review]
Great! could add comments inside the test methods in the future but look good.

**Review by Cessalan — APPROVED** [review]
C'est bon

**Review by HaroonMas — APPROVED** [review]
Everything looks good

**Review by ben-cl — APPROVED** [review]
Great! Resolve

**Review by Cessalan — APPROVED** [review]
Updated, conflict resolved.

**Review by LVoisard — APPROVED** [review]
nice

**Pull request merged**
