### PR TITLE
[SQTA27][TEAM C] Test if getVisitInternal returns new set<Visit> if null is entered

### PR DESCRIPTION
**Pull request by Cessalan**

### CODE REVIEW

**Review by LVoisard — DISMISSED** [review]
Nice work everything looks good!

**Review by HaroonMas — DISMISSED** [review]
Everything looks good

**Review by horiasandu1 — APPROVED** [review]
Conflicts have been resolved

**Review by LVoisard — APPROVED** [review]
Is ok for after review

**Pull request merged**
